[[mapping]]
topic = "emfcamp_announce/announcements"
[mapping.destination]
type = "rubric"
name = "emfcamp"
number = 1

[[mapping]]
topic = "emfcamp_announce/stage_a"
[mapping.destination]
type = "rubric"
name = "emfcamp"
number = 2

[[mapping]]
topic = "emfcamp_announce/stage_b"
[mapping.destination]
type = "rubric"
name = "emfcamp"
number = 3

[[mapping]]
topic = "emfcamp_announce/stage_c"
[mapping.destination]
type = "rubric"
name = "emfcamp"
number = 4

[[mapping]]
topic = "emfcamp_announce/workshop_1"
[mapping.destination]
type = "rubric"
name = "emfcamp"
number = 5

[[mapping]]
topic = "emfcamp_announce/workshop_2"
[mapping.destination]
type = "rubric"
name = "emfcamp"
number = 6

[[mapping]]
topic = "emfcamp_announce/workshop_3"
[mapping.destination]
type = "rubric"
name = "emfcamp"
number = 7

[[mapping]]
topic = "emfcamp_announce/m0nxn"
[mapping.destination]
type = "call"
recipients = ["m0nxn"]
transmitter_groups = ["uk-all"]
